name: arcesetc

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - h5py
#   - pip:
#       - dependency_from_pip
